CREATE TABLE IF NOT EXISTS public.financial_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ WITH TIME ZONE DEFAULT NOW() NOT NULL,
    ticker TEXT NOT NULL UNIQUE,
    name TEXT,
    sector TEXT,
    current_price NUMERIC,
    dividends_12m NUMERIC,
    price_history JSONB,
    dividend_history JSONB,
    last_updated_at TIMESTAMPTZ
);

-- Create an index for faster text searching on ticker and name
CREATE INDEX IF NOT EXISTS idx_financial_assets_search ON public.financial_assets USING GIN (to_tsvector('simple', ticker || ' ' || name));

-- Enable Row Level Security
ALTER TABLE public.financial_assets ENABLE ROW LEVEL SECURITY;

-- Create policies to allow users to read all assets but only manage their own (future-proofing)
CREATE POLICY "Allow authenticated read access" ON public.financial_assets FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin full access" ON public.financial_assets FOR ALL USING (false) WITH CHECK (false); -- Placeholder for admin roles
